yarn add @material-ui/core
yarn add @testing-library/jest-dom
yarn add @testing-library/react
yarn add @testing-library/user-event
yarn add aos
yarn add bootstrap
yarn add node-sass
yarn add pkg-dir
yarn add react
yarn add react-animated-cursor
yarn add react-dom
yarn add react-hook-form
yarn add react-modal
yarn add react-pwa-install
yarn add react-router-dom
yarn add react-scripts
yarn add react-slick
yarn add react-tabs
yarn add react-transition-group
yarn add slick-carousel
yarn add svgo
yarn add web-vitals